CREATE TABLE USERS
(
    ID               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRST_NAME       VARCHAR(30)                         NOT NULL,
    LAST_NAME        VARCHAR(30)                         NOT NULL,
    PHONE            VARCHAR(15) UNIQUE                  NOT NULL,
    MAIL             VARCHAR UNIQUE                      NOT NULL,
    PASSWORD         VARCHAR                             NOT NULL,

    AGE              INT CHECK (AGE > 0),
    COUNTRY          VARCHAR(30),
    CITY             VARCHAR(30),
    SCHOOL           VARCHAR(30),
    UNIVERSITY       VARCHAR(30),
    RELIGION         VARCHAR(30),

    DATE_REGISTERED  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATE_LAST_ACTIVE TIMESTAMP                           NOT NULL
);