CREATE TABLE USERS
(
    ID                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRST_NAME          VARCHAR(20)                         NOT NULL,
    LAST_NAME           VARCHAR(20)                         NOT NULL,
    PHONE               VARCHAR(20) UNIQUE                  NOT NULL,
    MAIL                VARCHAR(30) UNIQUE                  NOT NULL,
    PASSWORD            VARCHAR(30)                         NOT NULL,
    COUNTRY             VARCHAR(20),
    CITY                VARCHAR(20),
    AGE                 INT,
    DATE_REGISTERED     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATE_LAST_ACTIVE    TIMESTAMP                           NOT NULL,
    RELATIONSHIP_STATUS VARCHAR(20),
    RELIGION            VARCHAR(20),
    SCHOOL              VARCHAR(30),
    UNIVERSITY          VARCHAR(30)
);